### ISSUE TITLE
Texture Conversion

### ISSUE THREAD

**Issue by Nagell** [travnick/CryBlend#101]
I have all directories set (textures, rc and rc for textures).
While exporting RC doesn't show themself, and it does nothing.

Instead I get this warning: Resource compiler .ini files (Directort\Path\1 and Directory\Path\2) are not equal (file sizes are diferent).

Is it not natural that other versions of RC have other .ini files?

**Comment by Nagell** [comment]
Now I see that this is more complicated, beacuse CryBlend check bin32 and bin 64 directories... Why?

**Comment by Nagell** [comment]
Btw. after changing this ini files CryBlend doesn't use RC for textures anyway, so no RC is showing even if theres no warnings :/

**Comment by dwhite4** [comment]
Is this a CryBlend warning?  Or a CryEngine warning?

**Comment by Nagell** [comment]
I'm not sure but I can show you if tou have couple of minutes.

**Comment by Nagell** [comment]
Ok i found how to save consoles. It wasn't so hard :)

I'm adding two files (both with set rc and rc-textures):
- first with normal settings
- second with bin32\rc\rc.ini copied to bin64\rc\ (overwriting)

You can find both here: https://copy.com/jdqTiUAMXH2fDXRX

**Comment by dwhite4** [comment]
Hi Nagell, try this:
`1.) Import your textures into Gimp (PNG, JPG, etc.).
2.) Export your textures from Gimp as TIFF (LZW compression, as we discussed).
3.) Load the TIFF's over your existing textures in Blender.
4.) Export and select Convert Textures to DDS.
5.) You will see the texture conversion dialog appear...
    a.) Choose the correct image format RGB, RGBA, etc.
    b.) Choose the correct image type diff_lowQ, diff_highQ, norm_lowQ, etc.`

If you use this method, you can use RC v3.5+.  There is no need to replace any files.  This is the method I use.

**Comment by Nagell** [comment]
I still have the same problem - texture conversion dialog doesn't appear

Blender 2.73
All textures as .tif (LZW compression)
Both RC are 3.5.8.2310
Log is here: https://copy.com/jdqTiUAMXH2fDXRX

**Comment by dwhite4** [comment]
Just to make sure, are you using the .tif extension, not .tiff, correct?

**Comment by Nagell** [comment]
I was trying once all as .tif, and another time as .tiff. Both was wrong :/
Maybe send me your RC directory. RC and RC-textures should be the same, isn't it?

**Comment by dwhite4** [comment]
Use .tif (as .tiff seems to have some problems) for all future attempts.  Here are my RC files (I've included 32 and 64 bit versions depending on your system):
https://www.dropbox.com/sh/3x9zzlksduiztb2/AAAD39dwjAZaPgxXZ0xoLe4ua?dl=0
These are for v3.5.8.

Also, if this doesn't work, try using no compression instead of LWZ.

**Comment by Nagell** [comment]
Both doesn't work and with your RC to.
I'm not sure what could be different to your settings.

Mayby Skype-show step by step could solve this problem.
For us it is a big problem, because we can still use only old version of CryBlend :/

Or mayby you have any other idea?

**Comment by travnick** [comment]
What type of textures do you have assigned in Blender?

**Comment by Nagell** [comment]
Once diff, spec and norm. Other time only diff.
Both doesn't work.

**Comment by travnick** [comment]
I mean textures file formats, sorry.

**Comment by Nagell** [comment]
No problem. As I wrote to dwhite I was useing both tiff and tif (with and without compression). None of them makes Texture dialog appears.
