### ISSUE TITLE
CryBlend 5.1

### ISSUE THREAD

**Issue by feedbackex** [travnick/CryBlend#104]
Hi guys I add support some feature and fix some issues.
I don't find any connection with contributors, sorry for that and i share that here.
Supports --> Skeleton Animation, Skeleton Physic, Fix texture export.
and adding cycles render material node support.Information is in Fix.txt.
Link: http://afcstudio.org/CryBlend_v5.1.zip
Not:I test it with blender 2.72b and CryEngine 3.5.8
please report me for later versions.

**Comment by travnick** [comment]
Hi
Please create pull request on top of develop branch. In that way we are able to easily analyze changes you've made.

**Comment by feedbackex** [comment]
That take a moment for me :) maybe more. I will start to try.
