### ISSUE TITLE
Bone proxy and ik

### ISSUE THREAD

**Issue by feedbackex** [travnick/CryBlend#118]
New menu Edit Inverse Kinematics in Bone Utilities. That sets physic proxy and ik properties of selected bone in pose mode.

**Comment by Nagell** [comment]
Is this mean that skeleton and animation export still doesn't work even after your changes, sent as 5.1 via Dropbox? I'm asking because, one guy from my team have many problems with correctly bones exporting even without any animation.

**Comment by feedbackex** [comment]
Skeleton and Skeleton Animation works clearlly with  issue Skeleton Animation #117. This issue relative bone physic proxy (cylinder, capsule, sphere) and bone inverse kinematics (damping, spring, spring tension).

**Comment by Nagell** [comment]
Could you record short tutorial of how to make Armature with Mesh and export them properly (with import to CryEngine and info about versions of CryBlend, Blender and CryEngine)? It took us a whole  week without a good result :/ 

By the way, we noticed strange rotation of whole Armature - it could be repaired by Ctrl+N in edit mode and choosing option "Global +Y" but we also noticed others mistakes with bones... Mayday! Mayday, help us pls :)

**Comment by feedbackex** [comment]
Your meshes pivot point must be center. And skeleton have to be zero transformation. CryEngine 3.5.8 and up, Blender 2.70 and up, Cryblend 5.1.

**Comment by feedbackex** [comment]
You can temporarily download it my fork develop branch.

**Comment by feedbackex** [comment]
I published a video for Cryblend v5.1 about Skeleton and Animation.
Please tell me about result and CryEngine version you used.
Also you must download Cryblend in my develop branch.

**Comment by Nagell** [comment]
I was trying at Blender 2.70 and 2.75 and downloading from your repository branch "Release-5.1",
but i've got this:

Read new prefs: C:\Users\Toshiba\AppData\Roaming\Blender Foundation\Blender\2.70\config\userpref.blend
found bundled python: E:\Grafika\_BLENDERS\blender-2.70-windows64\2.70\python
Traceback (most recent call last):
  File "E:\Grafika\_BLENDERS\blender-2.70-windows64\2.70\scripts\modules\addon_utils.py", line 299, in enable
    mod = __import__(module_name)
  File "E:\Grafika\_BLENDERS\blender-2.70-windows64\2.70\scripts\addons\io_export_cryblend\__init__.py", line 1867
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

**Comment by feedbackex** [comment]
Sorry. I fixed that. Can you try again?

**Comment by Nagell** [comment]
Yop, now it works :) To be honest I was fixed it locally, but now your version works also.
Next tests i will make soon and give you feedback ;)

**Comment by Nagell** [comment]
Ok, all works almost perfect (skeletons, meshes and animations). 
Thank you for this great tutorial :D

There's only no possibility to create .chrparams by using an option in export menu. We're working with CryEngine 3.5.4 so we just need it.

Btw. There should be a popup info about missing ExportNode while I was trying to make Do Material Conversion. Something like: "You forget to add ExportNode. Do this before material conversion." Instead I've got some error and so on.

One more question: Is there any animation manager? I heard about it once, but couldnt find it.

**Comment by dwhite4** [comment]
Hi Nagell, I have a separate fork which includes export options to create a .chrparams on export.  When we release v5.1 we will merge these features.  Also, there is no Animation Manager in this release...possibly in a future release.

**Comment by feedbackex** [comment]
Thank you Nagell to test and feedback. I will add error message as soon about your suggestion.
And also thank you Daniel to clarify.

**Comment by Nagell** [comment]
Thats great. I will wait for 5.1 release impatiently :)
