### ISSUE TITLE
Reexport animation

### ISSUE THREAD

**Issue by feedbackex** [travnick/CryBlend#120]
Remove old .caf, .animsettings and .$animsettings files, if there are exist.
(Re export skeleton animaiton).
Not: That feature is not needed anymore with Character Tool which be introduced in CryEngine 3.7.0.

**Comment by Nagell** [comment]
Is there any possibility to export animation to CryEngine 3.5.4 or 2.5.8 (nonsteam)?

**Comment by feedbackex** [comment]
I don't have any idea. I test my issues with CryEngine 3.5.8 and 3.7.0, Blender 2.72, 2.74, 2.75.
I guess it must be worked with later 3.5.0 version. But I can not guarantee that.
