### ISSUE TITLE
Automatic Materials

### ISSUE THREAD

**Issue by dwhite4** [travnick/CryBlend#136]
Automatically names materials in the CryEngine convention on export.

**Comment by ochounos** [comment]
@dwhite4 After this change, materials are not well exported. In the mtl file, it adds a new entry for every object in the blender file and the name of all the materials are the name (group) of the cgf file.
In the .dae file, library_effects and library_materials contains one entry per object and the format name__001__name__1__material__phys... The second name__... is correct. Finally in the .mtl file, everything is cut as expected and you have the same number of materials as objects in the scene and all of them named as the name of the cgf file. Doesn't matter what you write in your material in blender. The export works whithout any error.

Do I missing something? Has the material convention changed?

**Comment by dwhite4** [comment]
@ochounos This change means you no longer need to use the material convention, it automatically creates it for you.  Just name your materials as you would normally in Blender.  For instance, don't name your material exportNode__id__materialName__physicsType.  Now just name your material materialName and optionally materialName__physicsType.

**Comment by ochounos** [comment]
Thank you for your reply, obviously I tried that and it's not working for me, as I said, doen't matter how you name your material, it's ignored. Also I have one entry per mesh in my scene and they are not grouped (let's say I have 7 meshes with two materials, I have 7 entries in my mtl file). Do you need a .blend sample file? Is it helping?

**Comment by feedbackex** [comment]
Hmm, material number (id) is important when reexport object without to change .mtl file that have set before on CryEngine. I guess, for that situation can be confusing. Is not ?

**Comment by ochounos** [comment]
OK, just material is duplicated, one per mesh. I use material1__physNone and material2__physNone.
I have added the blender sample and the mtl generated.

[cube.zip](https://github.com/travnick/CryBlend/files/129865/cube.zip)

**Comment by dwhite4** [comment]
Hmm, yes, I am aware of this duplicate issue and working on a fix.

**Comment by ochounos** [comment]
OK, nothing to say from my side then. Just we need to clear this to the users, the old files with old material notation are not exporting well anymore.
Thank you.

**Comment by dwhite4** [comment]
Alright, I believe I have fixed the issue.  You can find the new code under my branch feature/bugfixes.  Please test this and let me know.  I also made it so that it worked on the old material convention.

**Comment by ochounos** [comment]
Yes, I have tested, with old notation and new notation (with and without physics) and in all the cases it's working as expected.
Thank you very much!

**Comment by dwhite4** [comment]
No problem!  Thanks for your feedback, if you notice any other errors/inconveniences please report them here.

**Comment by feedbackex** [comment]
Hi, first of all thank you for attention @dwhite4 .

I think that transition is very radical. And have a lot of state problem and most important that not have backward compatibility.

My reviews:

1. Now, not working old blend files that have material name conventions.
2. Now, we can not determine global material name. (Ex: I want to use same material for a lot of architectural object and building, but now that not possible)
3. Now, I can not take submaterial advantage. (Ex: I want to use a submaterial that before already be created. And with old state, I set material name with submaterial number and name)

CryEngine do not use that kind of automation for that have very restriction.

Finally, I think automation have not competent advantages against to disadvantages?

For now, I suggest we must return old way.
Surely that method can be improved in future to adapt situations.
Specifically we can add a invisible switch mode logic for backward compatibility.

@ochounos, @travnick

**Comment by ochounos** [comment]
@feedbackex Please review if #149 solves the problem. Feel free to suggest more changes.

**Comment by feedbackex** [comment]
Hi @ochounos, Thank you for solving. But that way could override to add physic property for auto way.
I review and change a bit to fix.

**Comment by ochounos** [comment]
@feedbackex It's fixed already and also reorder is not working well. Give me a sec to apply more changes. Hold on.

**Comment by ochounos** [comment]
@feedbackex Please check the changes on the pull request #159 to see if it fixes your problems.

**Comment by ochounos** [comment]
Please, test and confirm if this issue can be closed now.

**Comment by ochounos** [comment]
Everything should be fixed on #159.
New notation allowed should be added to the documentation.

I think we can close this issue.

**Comment by dwhite4** [comment]
I agree.  Everything looks good.
