### ISSUE TITLE
Unnecessary Reprocess Fix for new RC system

### ISSUE THREAD

**Issue by feedbackex** [travnick/CryBlend#158]
Just chr and skin file have to be re processed by rc, dont require this
 for cgf file. That complicate console output and error tracing.

- Also add reexport animation support for CryEngine 3.5.8 and before.

- And constant variables rearranged.

**Comment by dwhite4** [comment]
@feedbackex when you are ready to merge, just send a pull request and I will merge.

**Comment by ochounos** [comment]
Seems that has been already merged 7 days ago in #161
In such case, this issue should be closed if no bug was found there.
If something needs to be fixed, please add this information here to track the issue.
