### ISSUE TITLE
Branches cleanup

### ISSUE THREAD

**Issue by ochounos** [travnick/CryBlend#178]
Let's remove unused branches in the project and keep only currently being in use: master, develop and maybe gh-pages.

Please review the branches that you were creating and take any action to keep the changes before the branch can be deleted. I will not delete any branch.

We should keep new feature branches in our own repositories and make pull requests when the feature is done. Let's keep cryblend repository as clean as possible.

**Comment by dwhite4** [comment]
@ochounos 

Good idea.  I deleted all of my branches.  But there are two remaining that are not mine:
revert-165-material-menu
revert-166-material-menu

**Comment by feedbackex** [comment]
```
revert-165-material-menu
revert-166-material-menu
```

I have deleted branches.

**Comment by feedbackex** [comment]
Now, there are left master, develop, gh-pages branches.
We may close issue.

**Comment by ochounos** [comment]
Thank you guys. Can be closed now.

Please @dwhite4 , create feature branches in your cloned repository and create pull requests to keep all the time the main repository clean.
