### ISSUE TITLE
Do material convention on one export node reverts material names in other export nodes

### ISSUE THREAD

**Issue by orhanod** [travnick/CryBlend#195]
Hi, 
I have a blender file with multiple objects, each in its individual export node. When I "do material convention" on one export node, material names in other export nodes revert to "un-conventioned" state. This makes it impossible to export many nodes at once.

Thanks for the great tool,

Orhan

**Comment by feedbackex** [comment]
Hi Orhan,

Thank you for your detailed bug reports. I will check it and spend time on it today.

**Comment by feedbackex** [comment]
Hi @orhanod, I have fixed it. Could you test it from my do-material-fix-for-multiple-node branch.

**Comment by orhanod** [comment]
Hi Özkan,

It looks ok now. Thanks for your interest and quick fix.

Orhan
