### ISSUE TITLE
Normals being split at UV seams

### ISSUE THREAD

**Issue by NikolaTLV** [travnick/CryBlend#204]
Hello. I am using cryblend 5.1 and noticed that normals are split along uv seams at export. When I use FBX to transfer model to CE everything works fine.

Cheers.

**Comment by feedbackex** [comment]
Hi @NikolaTLV, thank you for report,
I will be interested in for Version 5.3.

**Comment by NikolaTLV** [comment]
Great, thanks!

**Comment by feedbackex** [comment]
That issue has been included from #222 __Custom Normals__.
It will go on the Custom Normals issue.
