### ISSUE TITLE
Character physics proxies are not working

### ISSUE THREAD

**Issue by Hapexi** [travnick/CryBlend#231]
Character physics proxies are not working, they do not export. The reference file is not working either. Could really use a detailed documentation of this as well because in its current form there would be so many steps and there are no documentation of it.

**Comment by feedbackex** [comment]
Thank you @Hapexi, for reporting,
I will be interested in that.

**Comment by Hapexi** [comment]
I can also write the documentation if necessary when this feature is working for me so I know the workflow. 

Let me know if you need any log files or anything from me.

**Comment by feedbackex** [comment]
That would be great if,
I will make a feedback about that when I check the reference file.

**Comment by Hapexi** [comment]
Actually.. I am getting the same error "Wrong subset index in face... " in Maya as well.. Maybe this is a bug in the resource compiler?

**Comment by Hapexi** [comment]
Actually need to double check things because I got the same error in Maya when I had materials wrongly assigned to my physics geometry. I will report back when I have tried things again in Blender.

**Comment by feedbackex** [comment]
Hi @Hapexi ,
Thank you for feedback, the problem is incorrect material naming.
I have fixed it in #234 request.

**Comment by Hapexi** [comment]
Alright, I noticed it works and I got my own character working as well with proxies, thanks! I will write a tutorial of the proxy process once I play around with it a bit more.

**Comment by Hapexi** [comment]
I added a wiki page with a link to a video tutorial on how to add proxy geometry. 
https://github.com/travnick/CryBlend/wiki/Human-Biped

**Comment by feedbackex** [comment]
That's great, Thank you @Hapexi.
