### ISSUE TITLE
First added proxy geometry locks all the angles of that joint

### ISSUE THREAD

**Issue by Hapexi** [travnick/CryBlend#236]
I noticed an interesting behaviour with the joint limits. To which ever joint you first create a boneGeometry for has all of its angles locked afterwards. [Version hips](https://dl.dropboxusercontent.com/u/74485793/jointLimit1.JPG) In this picture I started adding boneGeometry from the hips, so hips as all of this angles locked. [Version shoulder](https://dl.dropboxusercontent.com/u/74485793/jointLimit2.JPG) In this version I started placing boneGeometry from the shoulder and it had all of its angles locked. Its afterwards impossible to edit the rotation limits of that bone. 

I guess its not that big of an issue if you start placing boneGeometry from a joint that does not rotate anyway.

**Comment by feedbackex** [comment]
Hi @Hapexi,
That behavior is related directly to CryEngine, I think, limit of first proxy must be __all angles locked.__
__CryEngine SDK Player__
![player_sdk](https://cloud.githubusercontent.com/assets/12111733/17380284/23c130de-59cf-11e6-9671-6c3138304c9d.jpg)

**Comment by Hapexi** [comment]
Alright, perfect then.
