### ISSUE TITLE
Issue with Outpipe.py

### ISSUE THREAD

**Issue by jsouth33** [travnick/CryBlend#252]
I had a problem loading the plugin because of outpipe.py being named outPipe.py, so I simply lowercased it and issue resolved. Also, in the "installation" file it doesn't say anything about having to enable the plugin. People new to blender need this because I had no idea where to go to get the plugin to work. Thanks.

**Comment by ajostergaard** [comment]
New to Cry* but if you tell me how to enable the plugin I'll push a pull request with the edits.

**Comment by jsouth33** [comment]
Go to file->User prefs->Add-ons, then simply click the box next to add-on name, and save.

**Comment by ajostergaard** [comment]
:) What's the correct name for the CryEngine game dev program? Editor? Sandbox?

**Comment by ajostergaard** [comment]
Adding this: "Then, in the CryEngine Sandbox, go to file->User prefs->Add-ons and tick the box to enable CryBlend, and save." - correct?

**Comment by ajostergaard** [comment]
Also, the latest source on here has outpipe.py in all lower case - the case was fixed on Feb 13th.

**Comment by ajostergaard** [comment]
https://github.com/travnick/CryBlend/pull/253
