### ISSUE TITLE
Can not activate the addon

### ISSUE THREAD

**Issue by DaskivuoS** [travnick/CryBlend#257]
cannot import name 'clock' from 'time' (unknown location)

this is the last line of the long description of the problem. I am using latest CryBlend issue with Blender 3.0

**Comment by travnick** [comment]
I'm really sorry, but the CryBlend is no longer actively maintained, so I'm unable to help you with the issue.
Feel free to grab the code and fix the issue.

**Comment by ghost** [comment]
This issue was already discussed here:
https://github.com/LeonidasWhite/BCRYExporter/pull/8/commits/ec19beda9f0067ee7df0681265380417f96d04b1

Hope it helps
