### ISSUE TITLE
New/Updated Tutorials

### ISSUE THREAD

**Issue by dwhite5914** [travnick/CryBlend#60]
Make new/updated tutorials for v5.0 and up (video and/or wiki) including tutorials on popular topics like:
- Characters
- FPS
- Vehicles

**Comment by dwhite4** [comment]
A preliminary CHR (character) tutorial:
https://www.dropbox.com/s/7zeq4jshtoa6ex2/character_tutorial.wmv?dl=0

**Comment by dwhite5914** [comment]
Going to open new issue...
