### ISSUE TITLE
Alpha test problem

### ISSUE THREAD

**Issue by Nagell** [travnick/CryBlend#67]
Hi, 

We have a big problem. We are using emissions stored in alpha channel of texture like it is described here:

http://docs.cryengine.com/display/SDKDOC2/Glow+Effect

In .png file all is ok, but after conversion to .dds all information about color at pixels with 0 alpha value are gone. I was checking it and problem is in .tiff files. Probably those are saved without alpha channel or with a wrong compression.

Now we are useing GIMP dds plugin to make it proper, and it works. But GIMP makes strange things with colors, like lower saturation and a sort of color correction which are also wrong. Better but still not good.

Is there any possibility to make it working?

Here you can see how I made this effect using GIMP (it's in polish but i think it is enough to catch the clue):

http://youtu.be/VOzNTi_gyb8

**Comment by dwhite4** [comment]
This has to do with process not CryBlend.  So I will close this issue.
