### ISSUE TITLE
Activating Add-On

### ISSUE THREAD

**Issue by IronElisha** [travnick/CryBlend#94]
I'm curious if this is something I'm missing or a bug. I get it when trying to enable the add-on. 

CryBlend v5.0
Blender v2.73 x64

![cryblend-screen](https://cloud.githubusercontent.com/assets/8468522/5690710/61649586-9863-11e4-96c5-e892a58e9793.png)

**Comment by dwhite4** [comment]
Hi Elisha, if you are replacing an existing CryBlend you will need to delete the one you had, so there is no io_export_cryblend folder in the add-ons, and then copy in the new io_export_cryblend folder.  You shouldn't have to do this in future releases.

**Comment by IronElisha** [comment]
Hmm - still getting the error with fresh installs and clean copy of the add-on. 

The add-on does not load in spite of the error.

**Comment by CTalvio** [comment]
Got the same issue, 4.13 initilizes fine, 5.0 does not.
First happened on a just installed blender 2.73 x64.

**Comment by travnick** [comment]
Maybe the quick workaround would help: rename `outPipe.py` to `outpipe.py`

**Comment by CTalvio** [comment]
Tried the workaround, cryblend now loads succesfully.

**Comment by dwhite4** [comment]
The release has been updated to include the bug fix.
