### ISSUE TITLE
TIF to DDS Converter

### ISSUE THREAD

**Issue by dwhite4** [travnick/CryBlend#96]
The TIF to DDS Converter was broken with the release of CryBlend v5.0.  It is only a simple error in the code that needs to be fixed (I'll be making some commits soon).  I intend to replace `dds_converter.py` with `rc.py` while making this fix (a file devoted to RC transactions).

**Comment by Nagell** [comment]
I found another bug. Mayby because of new version of Blender (2.75) 
Resource compiler from 3.5.8 after creating a tif files, says:

LibTIFF: Deflate compression support is not configured

so i don't get any dds :/
